<?php
/**
 * User: 陈晓发
 * Date: 2016/7/20
 * Time: 13:32
 */

namespace coswoole\base;


class CoThread extends \Coroutine
{
	public $threadPool = null;

	public function resume()
	{
		parent::resume(); // TODO: Change the autogenerated stub

		if ($this->status == self::STATUS_DEAD)
		{//回收
			$this->threadPool->releaseThread($this);
		}
	}
}