<?php
/**
 * User: 陈晓发
 * Date: 2016/7/20
 * Time: 13:24
 */

class WebThread extends \Coroutine
{
	public $response = null;
	public $request = null;
	public function __construct($callback=null)
	{
		parent::__construct([$this,'run']);
	}

	public function run()
	{
		$this->response->end('test');
	}

	private $_GET=[];
	private $_POST=[];
	private $_COOKIE=[];
	private $_SERVER=[];
	private $_FILES=[];
	public function resume()
	{
		if ($this->status != self::STATUS_SUSPEND)
		{
			return false;
		}
		$_TMP_GET = &$_GET;
		$_TMP_POST = &$_POST;
		$_TMP_COOKIE = &$_COOKIE;
		$_TMP_SERVER = &$_SERVER;
		$_TMP_FILES = &$_FILES;

		$_POST = &$this->_POST;
		$_GET = &$this->_GET;
		$_COOKIE = &$this->_COOKIE;
		$_SERVER = &$this->_SERVER;
		$_FILES = &$this->_FILES;

		parent::resume();

		$this->_POST = &$_POST;
		$this->_GET = &$_GET;
		$this->_COOKIE = &$_COOKIE;
		$this->_SERVER = &$_SERVER;
		$this->_FILES = &$_FILES;

		$_GET = &$_TMP_GET;
		$_POST = &$_TMP_POST;
		$_COOKIE = &$_TMP_COOKIE;
		$_SERVER = &$_TMP_SERVER;
		$_FILES = &$_TMP_FILES;


	}

	public function release()
	{
		$this->response = null;
		$this->request = null;

		$this->_POST = null;
		$this->_GET = null;
		$this->_COOKIE = null;
		$this->_SERVER = null;
		$this->_FILES = null;

	}


	/**
	 * 重置状态
	 * @param $request
	 * @param $response
	 */
	public function reset($request,$response)
	{
		$this->request = $request;
		$this->response = $response;

		$this->_GET = &$request->get;
		$this->_POST = &$request->post;
		$this->_SERVER = array_merge($request->server);
		$this->_COOKIE = &$request->cookie;

//		$this->_FILES = &$request->files;

		parent::reset(); // TODO: Change the autogenerated stub
	}
}