<?php
/**
 * User: 陈晓发
 * Date: 2016/7/20
 * Time: 13:24
 */

namespace coswoole\web;

use coswoole\app\HttpRequestHandler;
use coswoole\base\CoThread;

class WebThread extends CoThread
{
	public $handler = null;
	public function __construct($callback=null)
	{
		$this->handler = new HttpRequestHandler([]);
		parent::__construct([$this->handler,'run']);
	}

	private $_GET=[];
	private $_POST=[];
	private $_COOKIE=[];
	private $_SERVER=['SCRIPT_FILENAME'=>__DIR__.'/../yii2.0/web/index.php','SCRIPT_NAME'=>'index.php'];
	private $_FILES=[];
	public function resume()
	{
		if ($this->status != self::STATUS_SUSPEND)
		{
			return false;
		}
		$_TMP_GET = &$_GET;
		$_TMP_POST = &$_POST;
		$_TMP_COOKIE = &$_COOKIE;
		$_TMP_SERVER = &$_SERVER;
		$_TMP_FILES = &$_FILES;

		$_POST = &$this->_POST;
		$_GET = &$this->_GET;
		$_COOKIE = &$this->_COOKIE;
		$_SERVER = &$this->_SERVER;
		$_FILES = &$this->_FILES;

		parent::resume();

		$this->_POST = &$_POST;
		$this->_GET = &$_GET;
		$this->_COOKIE = &$_COOKIE;
		$this->_SERVER = &$_SERVER;
		$this->_FILES = &$_FILES;

		$_GET = &$_TMP_GET;
		$_POST = &$_TMP_POST;
		$_COOKIE = &$_TMP_COOKIE;
		$_SERVER = &$_TMP_SERVER;
		$_FILES = &$_TMP_FILES;


	}

	public function reset($request,$response)
	{
		$this->handler->requestInit($request,$response);
		parent::reset(); // TODO: Change the autogenerated stub
	}
}